server:
  port: 8089
corsPaths: "/**"
clientId: newClient
clientSecret: 259641ab-df6a-4c11-ad97-08dcf87579b6
authServer: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect
resources:
  - name: People Finder
    alias: peoplesvc
    server: ${PEOPLESVC_URL}/api
    healthUrl: ${PEOPLESVC_URL}/api/actuator/health
    route: /people
  - name: Manga Tracker
    alias: mangasvc
    server: ${MANGASVC_URL}/api
    healthUrl: ${MANGASVC_URL}/api/actuator/health
    route: /manga
